import 'package:lotus_core/lotus_core.dart';

/// Local-only fixtures used to exercise the map experience without writing to
/// Firestore. Dates are generated from [anchor] so the seed stays useful.
List<Event> buildDevelopmentEventSeed({DateTime? anchor}) {
  final today = _localDay(anchor ?? DateTime.now());
  return List.unmodifiable([
    _event(
      slug: 'aliados-sunset-sessions',
      title: 'Aliados Sunset Sessions',
      description: 'Concertos ao pôr do sol com artistas emergentes do Porto.',
      categoryId: 'musica',
      categoryLabel: 'Música',
      venue: 'Avenida dos Aliados',
      address: 'Praça General Humberto Delgado, Porto',
      latitude: 41.14974,
      longitude: -8.61024,
      startsAt: _at(today, 2, 19),
      endsAt: _at(today, 2, 23),
      price: EventPrice.free(),
      organizer: 'Porto Sounds',
      imageSeed: 'aliados-sunset',
      isFeatured: true,
    ),
    _event(
      slug: 'cedofeita-vinyl-night',
      title: 'Cedofeita Vinyl Night',
      description: 'Seleção de soul, disco e house exclusivamente em vinil.',
      categoryId: 'festas',
      categoryLabel: 'Festas',
      venue: 'Maus Hábitos',
      address: 'Rua de Passos Manuel 178, Porto',
      latitude: 41.14789,
      longitude: -8.60742,
      startsAt: _at(today, 3, 22),
      endsAt: _at(today, 4, 3),
      price: _paid(1200),
      organizer: 'Norte Clubbing',
      imageSeed: 'vinyl-night',
      ticketSlug: 'cedofeita-vinyl-night',
    ),
    _event(
      slug: 'ribeira-comedy-club',
      title: 'Ribeira Comedy Club',
      description: 'Uma noite de stand-up com novos talentos nacionais.',
      categoryId: 'comedia',
      categoryLabel: 'Comédia',
      venue: 'Hard Club',
      address: 'Mercado Ferreira Borges, Porto',
      latitude: 41.14128,
      longitude: -8.61548,
      startsAt: _at(today, 5, 21, 30),
      endsAt: _at(today, 5, 23, 30),
      price: _paid(1500),
      organizer: 'Rir no Norte',
      imageSeed: 'ribeira-comedy',
      ticketSlug: 'ribeira-comedy-club',
    ),
    _event(
      slug: 'bonfim-ceramics-lab',
      title: 'Bonfim Ceramics Lab',
      description: 'Workshop introdutório de cerâmica com materiais incluídos.',
      categoryId: 'workshops',
      categoryLabel: 'Workshops',
      venue: 'Opo’Lab Bonfim',
      address: 'Rua do Bonfim 134, Porto',
      latitude: 41.15182,
      longitude: -8.59685,
      startsAt: _at(today, 7, 15),
      endsAt: _at(today, 7, 18),
      price: _paid(2800),
      organizer: 'Mãos à Obra',
      imageSeed: 'ceramics-lab',
      ticketSlug: 'bonfim-ceramics-lab',
    ),
    _event(
      slug: 'casa-da-musica-open-air',
      title: 'Open Air na Boavista',
      description: 'Eletrónica melódica e projeções visuais ao ar livre.',
      categoryId: 'musica',
      categoryLabel: 'Música',
      venue: 'Praça de Mouzinho de Albuquerque',
      address: 'Rotunda da Boavista, Porto',
      latitude: 41.15794,
      longitude: -8.62911,
      startsAt: _at(today, 9, 18),
      endsAt: _at(today, 9, 23),
      price: _paid(1800),
      organizer: 'Boavista Cultural',
      imageSeed: 'boavista-open-air',
      ticketSlug: 'casa-da-musica-open-air',
      isFeatured: true,
    ),
    _event(
      slug: 'palacio-cristal-yoga',
      title: 'Yoga ao Amanhecer',
      description: 'Sessão orientada nos jardins com vista para o Douro.',
      categoryId: 'desporto',
      categoryLabel: 'Desporto',
      venue: 'Jardins do Palácio de Cristal',
      address: 'Rua de Dom Manuel II 282, Porto',
      latitude: 41.14693,
      longitude: -8.62531,
      startsAt: _at(today, 10, 8),
      endsAt: _at(today, 10, 9, 15),
      price: EventPrice.free(),
      organizer: 'Move Porto',
      imageSeed: 'cristal-yoga',
    ),
    _event(
      slug: 'bolhao-tasting-route',
      title: 'Sabores do Bolhão',
      description: 'Rota guiada por produtores e sabores tradicionais.',
      categoryId: 'gastronomia',
      categoryLabel: 'Gastronomia',
      venue: 'Mercado do Bolhão',
      address: 'Rua Formosa 322, Porto',
      latitude: 41.14995,
      longitude: -8.60658,
      startsAt: _at(today, 11, 12),
      endsAt: _at(today, 11, 15),
      price: _paid(2200),
      organizer: 'Porto à Mesa',
      imageSeed: 'bolhao-tasting',
      ticketSlug: 'bolhao-tasting-route',
    ),
    _event(
      slug: 'batalha-short-films',
      title: 'Curtas à Meia-Noite',
      description: 'Seleção de cinema independente português e europeu.',
      categoryId: 'cultura',
      categoryLabel: 'Cultura',
      venue: 'Batalha Centro de Cinema',
      address: 'Praça da Batalha 47, Porto',
      latitude: 41.14563,
      longitude: -8.60731,
      startsAt: _at(today, 12, 23),
      endsAt: _at(today, 13, 1),
      price: _paid(800),
      organizer: 'Cinema Porto',
      imageSeed: 'batalha-films',
      ticketSlug: 'batalha-short-films',
    ),
    _event(
      slug: 'sao-bento-history-walk',
      title: 'Porto em Camadas',
      description:
          'Passeio pela história escondida da Baixa e dos seus azulejos.',
      categoryId: 'cultura',
      categoryLabel: 'Cultura',
      venue: 'Estação de São Bento',
      address: 'Praça de Almeida Garrett, Porto',
      latitude: 41.14561,
      longitude: -8.61058,
      startsAt: _at(today, 14, 10),
      endsAt: _at(today, 14, 12, 30),
      price: EventPrice.free(),
      organizer: 'Porto a Pé',
      imageSeed: 'porto-history',
    ),
    _event(
      slug: 'rivoli-new-stage',
      title: 'Palco Novo',
      description: 'Criação contemporânea que cruza teatro, dança e música.',
      categoryId: 'teatro',
      categoryLabel: 'Teatro',
      venue: 'Teatro Municipal Rivoli',
      address: 'Praça de D. João I, Porto',
      latitude: 41.14862,
      longitude: -8.60954,
      startsAt: _at(today, 16, 21),
      endsAt: _at(today, 16, 22, 40),
      price: _range(1000, 1800),
      organizer: 'Cultura em Cena',
      imageSeed: 'rivoli-stage',
      ticketSlug: 'rivoli-new-stage',
      isFeatured: true,
    ),
    _event(
      slug: 'virtudes-picnic-jazz',
      title: 'Picnic Jazz nas Virtudes',
      description: 'Jazz descontraído com músicos locais e entrada livre.',
      categoryId: 'musica',
      categoryLabel: 'Música',
      venue: 'Passeio das Virtudes',
      address: 'Passeio das Virtudes 53, Porto',
      latitude: 41.14392,
      longitude: -8.62009,
      startsAt: _at(today, 18, 17),
      endsAt: _at(today, 18, 20),
      price: EventPrice.free(),
      organizer: 'Jazz ao Norte',
      imageSeed: 'virtudes-jazz',
    ),
    _event(
      slug: 'foz-night-run',
      title: 'Foz Night Run',
      description: 'Corrida urbana de 7 km junto ao Atlântico.',
      categoryId: 'desporto',
      categoryLabel: 'Desporto',
      venue: 'Jardim do Passeio Alegre',
      address: 'Rua do Passeio Alegre 828, Porto',
      latitude: 41.14815,
      longitude: -8.67254,
      startsAt: _at(today, 19, 20, 30),
      endsAt: _at(today, 19, 22),
      price: _paid(1000),
      organizer: 'Run Porto',
      imageSeed: 'foz-night-run',
      ticketSlug: 'foz-night-run',
    ),
    _event(
      slug: 'serralves-photo-walk',
      title: 'Photo Walk em Serralves',
      description:
          'Percurso fotográfico orientado pelos jardins e arquitetura.',
      categoryId: 'workshops',
      categoryLabel: 'Workshops',
      venue: 'Fundação de Serralves',
      address: 'Rua de Dom João de Castro 210, Porto',
      latitude: 41.15965,
      longitude: -8.65968,
      startsAt: _at(today, 21, 10),
      endsAt: _at(today, 21, 13),
      price: _paid(1600),
      organizer: 'Olhar Norte',
      imageSeed: 'serralves-photo',
      ticketSlug: 'serralves-photo-walk',
    ),
    _event(
      slug: 'gaia-rooftop-party',
      title: 'Gaia Rooftop Party',
      description: 'DJ sets com vista panorâmica sobre o Porto e o Douro.',
      categoryId: 'festas',
      categoryLabel: 'Festas',
      venue: 'WOW Porto',
      address: 'Rua do Choupelo 39, Vila Nova de Gaia',
      latitude: 41.13396,
      longitude: -8.61386,
      startsAt: _at(today, 23, 20),
      endsAt: _at(today, 24, 2),
      price: _paid(2000),
      organizer: 'Douro Nights',
      imageSeed: 'gaia-rooftop',
      ticketSlug: 'gaia-rooftop-party',
      isFeatured: true,
    ),
    _event(
      slug: 'jardim-morro-acoustic',
      title: 'Acústico no Jardim do Morro',
      description: 'Fim de tarde acústico com cantautores portugueses.',
      categoryId: 'musica',
      categoryLabel: 'Música',
      venue: 'Jardim do Morro',
      address: 'Avenida da República, Vila Nova de Gaia',
      latitude: 41.13802,
      longitude: -8.60923,
      startsAt: _at(today, 25, 18, 30),
      endsAt: _at(today, 25, 21),
      price: EventPrice.free(),
      organizer: 'Gaia Cultura',
      imageSeed: 'morro-acoustic',
    ),
    _event(
      slug: 'mafamide-street-food',
      title: 'Mafamude Street Food',
      description: 'Cozinhas do mundo, música e propostas vegetarianas.',
      categoryId: 'gastronomia',
      categoryLabel: 'Gastronomia',
      venue: 'Praça da República',
      address: 'Praça da República, Vila Nova de Gaia',
      latitude: 41.12487,
      longitude: -8.60591,
      startsAt: _at(today, 27, 12),
      endsAt: _at(today, 27, 22),
      price: EventPrice.free(),
      organizer: 'Gaia à Mesa',
      imageSeed: 'mafamide-food',
    ),
    _event(
      slug: 'calem-fado-session',
      title: 'Fado nas Caves',
      description:
          'Prova comentada acompanhada por uma sessão intimista de fado.',
      categoryId: 'cultura',
      categoryLabel: 'Cultura',
      venue: 'Caves Cálem',
      address: 'Avenida de Diogo Leite 344, Vila Nova de Gaia',
      latitude: 41.13841,
      longitude: -8.61164,
      startsAt: _at(today, 30, 19),
      endsAt: _at(today, 30, 21),
      price: _paid(2500),
      organizer: 'Douro Vivo',
      imageSeed: 'calem-fado',
      ticketSlug: 'calem-fado-session',
    ),
    _event(
      slug: 'heroismo-improv-theatre',
      title: 'Improviso no Heroísmo',
      description:
          'Espetáculo de improvisação construído com sugestões do público.',
      categoryId: 'teatro',
      categoryLabel: 'Teatro',
      venue: 'Casa d’Artes do Bonfim',
      address: 'Rua do Heroísmo 211, Porto',
      latitude: 41.14709,
      longitude: -8.59218,
      startsAt: _at(today, 33, 21, 30),
      endsAt: _at(today, 33, 23),
      price: _paid(1100),
      organizer: 'Cena Aberta',
      imageSeed: 'heroismo-improv',
      ticketSlug: 'heroismo-improv-theatre',
    ),
  ]);
}

Event _event({
  required String slug,
  required String title,
  required String description,
  required String categoryId,
  required String categoryLabel,
  required String venue,
  required String address,
  required double latitude,
  required double longitude,
  required DateTime startsAt,
  required DateTime endsAt,
  required EventPrice price,
  required String organizer,
  required String imageSeed,
  String? ticketSlug,
  bool isFeatured = false,
}) {
  return Event(
    id: 'dev-events/$slug',
    title: title,
    description: description,
    categories: [EventCategory(id: categoryId, label: categoryLabel)],
    location: EventLocation(
      displayName: venue,
      venueName: venue,
      address: address,
      city: address.contains('Gaia') ? 'Vila Nova de Gaia' : 'Porto',
      countryCode: 'PT',
      coordinates: GeoCoordinates(latitude: latitude, longitude: longitude),
    ),
    startsAt: startsAt,
    endsAt: endsAt,
    imageUri: Uri.https('picsum.photos', '/seed/$imageSeed/800/600'),
    price: price,
    organizer: EventOrganizer(
      id: 'dev-organizers/${_slug(organizer)}',
      name: organizer,
    ),
    links: ticketSlug == null
        ? const []
        : [
            EventLink(
              kind: EventLinkKind.tickets,
              uri: Uri.https('example.com', '/lotus-dev/$ticketSlug'),
            ),
          ],
    status: EventStatus.published,
    ticketAvailability: ticketSlug == null
        ? TicketAvailability.unknown
        : TicketAvailability.available,
    isFeatured: isFeatured,
    popularityScore: isFeatured ? 90 : 45,
  );
}

DateTime _localDay(DateTime value) {
  final local = value.toLocal();
  return DateTime(local.year, local.month, local.day);
}

DateTime _at(DateTime day, int offsetDays, int hour, [int minute = 0]) =>
    DateTime(day.year, day.month, day.day + offsetDays, hour, minute);

EventPrice _paid(int cents) => EventPrice(
  currencyCode: 'EUR',
  minimumMinorUnits: cents,
  maximumMinorUnits: cents,
);

EventPrice _range(int minimum, int maximum) => EventPrice(
  currencyCode: 'EUR',
  minimumMinorUnits: minimum,
  maximumMinorUnits: maximum,
);

String _slug(String value) => value
    .toLowerCase()
    .replaceAll(RegExp(r'[^a-z0-9]+'), '-')
    .replaceAll(RegExp(r'^-|-$'), '');
